# Generated by Django 4.2.4 on 2023-09-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slack',
            old_name='github_url',
            new_name='github_file_url',
        ),
        migrations.RenameField(
            model_name='slack',
            old_name='source_code',
            new_name='github_repo_url',
        ),
        migrations.RenameField(
            model_name='slack',
            old_name='time',
            new_name='utc_time',
        ),
        migrations.RemoveField(
            model_name='slack',
            name='day_week',
        ),
        migrations.AddField(
            model_name='slack',
            name='current_day',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
